version: "3.3"

services:
  dawn_db_server:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_USER: root
      MYSQL_DATABASE: alpha_db
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
    secrets:
      - mysql_secret
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    ports:
      - 3307:3306

secrets:
  mysql_secret:
    file: mysql_secret
